<?php /** @var null $model */ ?>

<h1>JSON Demo</h1>
<button id="btGetRandomPerson">Get Random Person</button>
<div id="divResult"></div>

<script src="<?= Configuration::webUrl ?>js/jquery-2.1.4.min.js"></script>
<script>

    var btGetRandomPerson = null;
    var divResult = null;

    window.addEventListener('DOMContentLoaded', function()
    {
        btGetRandomPerson = document.getElementById('btGetRandomPerson');
        divResult = document.getElementById('divResult');
        btGetRandomPerson.addEventListener('click', getRandomPerson);
    });

    function getRandomPerson()
    {
        $.getJSON("<?= NavigationHelper::getLink(array('JsonDemo', 'GetRandomPerson')) ?>", function(result)
        {
            var html = "";
            html += "<p>Name: <strong>" + result.name + " " + result.surname + "<\/strong><\/p>";
            html += "<p>City: <strong>" + result.city + "<\/strong><\/p>";
            html += "<p>Hobbies:<ul>";
            for (var i = 0; i < result.hobbies.length; i++)
            {
                html += "<li>" + result.hobbies[i] + "<\/li>";
            }
            html += "<\/ul><\/p>";
            html += "<p>Received: <strong>" + JSON.stringify(result) + "<\/strong><\/p>";
            divResult.innerHTML = html;
        });
    }

</script>