<?php /** @var RouteDemoMessagesViewModel $model */ ?>
<h1><?= $model->subtopicTitle ?></h1>
<h3><a href="<?= NavigationHelper::getLink(array('RouteDemo', "{$model->topicId}")) ?>">Back</a></h3>
<?php for ($i = 0, $end = count($model->messages); $i < $end; $i++): ?>
    <a style="color: black; text-decoration: none" href="<?= NavigationHelper::getLink(array('RouteDemo', "{$model->topicId}-{$model->subtopicId}-{$i}")) ?>">
        <div style="background-color: <?php if ($model->highlightedMessageId === $i) echo 'yellow'; else echo 'aquamarine'; ?>">
            <p>User: <?= $model->messages[$i]->user ?></p>
            <h3><?= $model->messages[$i]->message ?></h3>
        </div>
    </a>
<?php endfor; ?>