<?php /** @var RouteDemoSubtopicsViewModel $model */ ?>
<h1>Subtopics (<?= $model->topicTitle ?>)</h1>
<h3><a href="<?= NavigationHelper::getLink(array('RouteDemo')) ?>">Back</a></h3>
<?php for ($i = 0, $end = count($model->subtopics); $i < $end; $i++): ?>
    <a style="color: black; text-decoration: none" href="<?= NavigationHelper::getLink(array('RouteDemo', "{$model->topicId}-{$i}")) ?>">
        <div style="background-color: aquamarine;">
            <h3><?= $model->subtopics[$i]->title ?> (<?= $model->subtopics[$i]->messagesCount ?>)</h3>
        </div>
    </a>
<?php endfor; ?>