<?php /** @var SessionDemoViewModel $model */ ?>
<h1>Session Demo</h1>
<p>Hi <strong><?= $model->name ?></strong>!</p>

<form method="post" action="<?= UrlHelper::getLink(array('SessionDemo', 'ChangeName')) ?>">
    <input name="frmChangeName" type="hidden" value="1"/>
    <input name="txtName" type="text" />
    <input name="btChange" type="submit" value="Change the Session!" />
</form>

<a href="<?= UrlHelper::getLink(array('SessionDemo', 'DeleteName')) ?>">Delete the Session</a>