<?php /** @var RouteDemoTopicsViewModel $model */ ?>
<h1>Topics</h1>
<?php for ($i = 0, $end = count($model->topics); $i < $end; $i++): ?>
    <a style="color: black; text-decoration: none" href="<?= UrlHelper::getLink(array('RouteDemo', $i)) ?>">
        <div style="background-color: aquamarine;">
            <h3><?= $model->topics[$i]->title ?> (<?= $model->topics[$i]->subtopicsCount ?>)</h3>
            <p>
                <?= $model->topics[$i]->description ?><br/>
            </p>
        </div>
    </a>
<?php endfor; ?>