<meta charset="UTF-8" />
<meta name="description" content="Tienda Igara" />
<meta name="keywords" content="Tienda, Online, Imprenta, Igara" />
<meta name="author" content="Ivan Sanz - ivansanzcarasa@gmail.com" />

<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />

<script src="<?= Configuration::webUrl ?>js/jquery-2.1.4.min.js"></script>
<script src="<?= Configuration::webUrl ?>js/iscFramework.js"></script>