<?php /** @var CookieDemoViewModel $model */ ?>
<h1>Cookie Demo</h1>
<p>Hi <strong><?= $model->name ?></strong>!</p>

<form method="post" action="<?= UrlHelper::getLink(array('CookieDemo', 'ChangeName')) ?>">
    <input name="frmChangeName" type="hidden" value="1"/>
    <input name="txtName" type="text" />
    <input name="btChange" type="submit" value="Change my name!" />
</form>

<a href="<?= UrlHelper::getLink(array('CookieDemo', 'DeleteName')) ?>">Delete my name</a>