<?php /** @var CookieDemoViewModel $model */ ?>
<h1>Hi <?= FormatHelper::cleanOutput($model->name) ?>!</h1>

<form method="post" action="<?= NavigationHelper::getLink(array('CookieDemo', 'ChangeName')) ?>">
    <input name="frmChangeName" type="hidden" value="1"/>
    <input name="txtName" type="text" />
    <input name="btChange" type="submit" value="Change the Cookie!" />
</form>

<a href="<?= NavigationHelper::getLink(array('CookieDemo', 'DeleteName')) ?>">Delete the cookie</a>